import java.io.IOException

fun main (args: Array<String>) {
/*
    fun foo() {
        throw IOException()
    }

    fun bar() {
        foo () //no need to surround method with try-catch block
    }


    fun sendFormData(user: User?, data: Data?) { // 1
        user ?: throw NullPointerException("User cannot be null") // 2
        data ?: throw NullPointerException("Data cannot be null")

        //do something

    }

    fun onSendDataClicked() {
        try { // 3
            sendFormData(user, data)
        } catch (e: AssertionError) { // 4
            // handle error
        } finally { // 5
            // optional finally block
        }
    }

    val result = try { // 1
        context.packageManager.getPackageInfo("com.text.app", 0) //2
        true
    } catch (ex: PackageManager.NameNotFoundException) { // 3
        false
    }

    const val MAX_LOG_ENTRIES = 100

        @MyLogger(MAX_LOG_ENTRIES)
        class Test()
*/
}